# Generated by Django 6.0.3 on 2026-04-19 21:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('k', models.DecimalField(decimal_places=4, help_text='Coefficient de transmission surfacique (k).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOuvrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('k', models.DecimalField(decimal_places=4, help_text='Coefficient de transmission surfacique (k).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePlancher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('k', models.DecimalField(decimal_places=4, help_text='Coefficient de transmission surfacique (k).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeToiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('k', models.DecimalField(decimal_places=4, help_text='Coefficient de transmission surfacique (k).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('surface_habitable_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Surface habitable (m²)')),
                ('surface_plancher_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Surface plancher (m²)')),
                ('surface_mur_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Surface murs (m²)')),
                ('surface_toiture_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Surface toiture (m²)')),
                ('surface_ouvrants_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Surface ouvrants (m²)')),
                ('type_mur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thermo.typemur')),
                ('type_ouvrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thermo.typeouvrant')),
                ('type_plancher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thermo.typeplancher')),
                ('type_toiture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thermo.typetoiture')),
            ],
            options={
                'ordering': ['-cree_le', 'nom'],
            },
        ),
    ]
